name: Daily Fear and Greed Update

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정(UTC)에 실행
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt google-genai
      - name: Run script
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_INDEX_ADVISOR_KEY }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: python -c 'from main import update_fng; update_fng()'
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public/gemini_snp_adv.html public/gemini_snp_adv_ko_en.html
          git commit -m "Auto-update US Gemini advisor report: $(date +'%Y-%m-%d')" || exit 0
          git pull --rebase
          git push
